events {
  worker_connections 1024; # número máximo de conexões simultâneas por worker
}

http {

  upstream wordpress {
    server wordpress1;
    #server wordpress2;
    #server wordpress3;
  }

  server { # configuração do servidor nginx
    listen 80 default_server; # escuta na porta 80
    listen [::]:80 default_server; # escuta também para IPv6

    root /usr/share/nginx/html; # pasta de arquivos estáticos
    index index.php; # arquivo padrão

    location / {
      add_header X-Upstream $upstream_addr; 
      proxy_set_header Host $host; 
      proxy_set_header X-Real-IP $remote_addr; 
      proxy_set_header x-forwarded-for $proxy_add_x_forwarded_for;
      proxy_pass http://wordpress;
    }
  }
}